[project]
name = "finite-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "latexify-py>=0.4.4",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
]
